# Generated by Django 6.0.4 on 2026-04-18 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assetitem_low_stock_threshold_assetaccountability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountability',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_accountability_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='approved', max_length=20),
        ),
    ]
