# Generated by Django 6.0.4 on 2026-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assetreturnproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
