# Generated by Django 6.0.4 on 2026-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_assetreturnproof_image_clientdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdeletionrequest',
            name='resubmission_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
