# Generated by Django 6.0.4 on 2026-04-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_developmentfeedbackcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchNoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patch_note_comments_created', to=settings.AUTH_USER_MODEL)),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.patchnote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatchNoteReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like')], default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_note_reactions_created', to=settings.AUTH_USER_MODEL)),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.patchnote')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('patch_note', 'created_by', 'reaction'), name='unique_patch_note_reaction_per_user')],
            },
        ),
    ]
