# Generated by Django 6.0.4 on 2026-04-20 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_patchnotecomment_patchnotereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patchnotereaction',
            name='unique_patch_note_reaction_per_user',
        ),
        migrations.AlterField(
            model_name='patchnotereaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('celebrate', 'Celebrate'), ('insightful', 'Insightful')], default='like', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='patchnotereaction',
            constraint=models.UniqueConstraint(fields=('patch_note', 'created_by'), name='unique_patch_note_reaction_per_user'),
        ),
    ]
