# Generated by Django 6.0.4 on 2026-04-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_patchnoteattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInternetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=120)),
                ('website_url', models.URLField(blank=True)),
                ('account_identifier', models.CharField(help_text='Main login identifier (username/email/phone).', max_length=190)),
                ('login_email', models.EmailField(blank=True, max_length=254)),
                ('auth_provider', models.CharField(choices=[('native', 'Native Username/Password'), ('google', 'Sign in with Google'), ('facebook', 'Sign in with Facebook'), ('microsoft', 'Sign in with Microsoft'), ('apple', 'Sign in with Apple'), ('other', 'Other SSO/Provider')], default='native', max_length=24)),
                ('credential_username', models.CharField(blank=True, max_length=190)),
                ('encrypted_password', models.TextField()),
                ('holder_name_override', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('last_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_internet_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('reveal_companyinternetaccount_password', 'Can reveal company internet account passwords')],
            },
        ),
    ]
