# Generated by Django 6.0.4 on 2026-04-23 00:00

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_companyinternetaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary Backup Schedule', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('cron_minute', models.PositiveSmallIntegerField(default=0)),
                ('max_backups', models.PositiveSmallIntegerField(default=10)),
                ('include_logs', models.BooleanField(default=True)),
                ('include_docs', models.BooleanField(default=True)),
                ('include_media', models.BooleanField(default=True)),
                ('include_database', models.BooleanField(default=True)),
                ('include_static', models.BooleanField(default=False)),
                ('include_templates', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_backup_schedules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=180)),
                ('archive', models.FileField(upload_to=core.models.system_backup_upload_to)),
                ('included_scopes', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_restored_at', models.DateTimeField(blank=True, null=True)),
                ('restore_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_backups_created', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.systembackupschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
