# Generated by Django 6.0.4 on 2026-04-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_system_backup_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembackupschedule',
            name='job_type',
            field=models.CharField(
                choices=[
                    ('backup_only', 'Backup Only'),
                    ('backup_cleanup', 'Backup + Cleanup'),
                    ('backup_verify', 'Backup + Verify'),
                ],
                default='backup_cleanup',
                max_length=20,
            ),
        ),
    ]
