# Generated by Django 6.0.4 on 2026-04-24 06:47

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_assetitemtype_view_category_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(editable=False, max_length=9, unique=True)),
                ('request_year', models.PositiveIntegerField(db_index=True, editable=False)),
                ('serial_sequence', models.PositiveIntegerField(editable=False)),
                ('requester_name', models.CharField(max_length=150)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('department', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundRequestLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.fundrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FundRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fund Request Template', max_length=150)),
                ('file', models.FileField(upload_to=core.models.fund_request_template_upload_to)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_request_templates_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_requests', to='core.fundrequesttemplate'),
        ),
        migrations.AddConstraint(
            model_name='fundrequest',
            constraint=models.UniqueConstraint(fields=('request_year', 'serial_sequence'), name='unique_fund_request_year_sequence'),
        ),
    ]
