# Generated by Django 6.0.4 on 2026-04-28 09:54

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_accountability_control_numbers(apps, schema_editor):
    AssetAccountability = apps.get_model('core', 'AssetAccountability')
    sequences_by_year = {}
    for accountability in AssetAccountability.objects.order_by('date_borrowed', 'id'):
        if accountability.control_number and accountability.request_year and accountability.control_sequence:
            continue
        borrowed_at = accountability.date_borrowed
        if borrowed_at:
            try:
                borrowed_at = timezone.localtime(borrowed_at)
            except ValueError:
                pass
            year = borrowed_at.year
        else:
            year = timezone.localdate().year
        sequences_by_year[year] = sequences_by_year.get(year, 0) + 1
        sequence = sequences_by_year[year]
        accountability.request_year = year
        accountability.control_sequence = sequence
        accountability.control_number = f'AA-{year}-{sequence:04d}'
        accountability.save(update_fields=['request_year', 'control_sequence', 'control_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_databasefile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccountabilityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asset Accountability Template', max_length=150)),
                ('file', models.FileField(upload_to=core.models.accountability_template_upload_to)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='control_number',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='control_sequence',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='request_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_accountability_control_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assetaccountability',
            constraint=models.UniqueConstraint(fields=('request_year', 'control_sequence'), name='unique_accountability_year_sequence'),
        ),
        migrations.AddField(
            model_name='assetaccountabilitytemplate',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_accountability_templates_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
