# Generated by Django 6.0.4 on 2026-04-28 09:57

from django.db import migrations, models


def backfill_accountability_person_details(apps, schema_editor):
    AssetAccountability = apps.get_model('core', 'AssetAccountability')
    for accountability in AssetAccountability.objects.select_related('borrowed_by', 'item__department'):
        user = accountability.borrowed_by
        if user:
            full_name = f'{(user.first_name or "").strip()} {(user.last_name or "").strip()}'.strip()
            accountability.accountable_name = full_name or user.username
        else:
            accountability.accountable_name = ''
        accountability.department = getattr(accountability.item.department, 'name', '') if accountability.item_id else ''
        accountability.save(update_fields=['accountable_name', 'department'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_assetaccountabilitytemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountability',
            name='accountable_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='position_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(backfill_accountability_person_details, migrations.RunPython.noop),
    ]
