# Generated by Django 6.0.4 on 2026-04-28 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_assetaccountability_accountable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountability',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
