# Generated by Django 6.0.4 on 2026-04-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_accountability_control_number_approval_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccountability',
            name='return_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='return_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='return_date_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='return_received_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='return_remarks',
            field=models.TextField(blank=True),
        ),
    ]
