# Generated by Django 6.0.4 on 2026-04-29 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_assetaccountability_return_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccountabilityFormBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('request_year', models.PositiveIntegerField(db_index=True, editable=False)),
                ('control_sequence', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_accountability_form_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetaccountability',
            name='accountability_form_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_records', to='core.assetaccountabilityformbatch'),
        ),
        migrations.AddConstraint(
            model_name='assetaccountabilityformbatch',
            constraint=models.UniqueConstraint(fields=('request_year', 'control_sequence'), name='unique_accountability_form_batch_year_sequence'),
        ),
    ]
