# Generated by Django 6.0.4 on 2026-04-30 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_assetaccountabilityformbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('submit', 'Submitted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('cancel', 'Cancelled'), ('generate', 'Generated'), ('upload', 'Uploaded'), ('restore', 'Restored'), ('archive', 'Archived'), ('status_change', 'Status Changed'), ('role_change', 'Role Changed'), ('security', 'Security')], db_index=True, max_length=32)),
                ('category', models.CharField(choices=[('clients', 'Clients'), ('finance', 'Finance'), ('assets', 'Asset Tracker'), ('accountability', 'Accountability'), ('support', 'Support Tickets'), ('development', 'Development'), ('system', 'System'), ('users', 'Users & Roles'), ('security', 'Security')], db_index=True, max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('target_model', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('url_name', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['category', '-created_at'], name='core_activi_categor_969ef1_idx'), models.Index(fields=['action', '-created_at'], name='core_activi_action_a01617_idx')],
            },
        ),
    ]
