# Generated by Django 6.0.4 on 2026-04-30 14:56

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorageEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('destination_path', models.CharField(help_text='Destination device/path label (e.g., Drive D, NAS-01, Cloud Bucket A).', max_length=255)),
                ('capacity_mb', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_storage_endpoints_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFileNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('node_type', models.CharField(choices=[('folder', 'Folder'), ('shared_folder', 'Shared Folder'), ('file', 'File')], default='folder', max_length=20)),
                ('access_scope', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=20)),
                ('branch_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('department_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('role_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.file_manager_upload_to)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_file_nodes_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_file_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.managedfilenode')),
                ('storage_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='core.filestorageendpoint')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_file_nodes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'View/Read'), ('write', 'Write'), ('read_write', 'Read/Write')], default='read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_file_permissions_created', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.managedfilenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_file_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['node_id', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='managedfilenode',
            constraint=models.UniqueConstraint(fields=('parent', 'owner', 'name'), name='unique_managed_file_node_per_owner_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='managedfilepermission',
            constraint=models.UniqueConstraint(fields=('node', 'user'), name='unique_managed_file_permission_per_user_node'),
        ),
    ]
