# Generated by Django 6.0.4 on 2026-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_superuserchatreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuserchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='super_user_chat_images/'),
        ),
        migrations.AlterField(
            model_name='superuserchatmessage',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
