# Generated by Django 6.0.4 on 2026-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_superuserchatmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_ticket_message_images/'),
        ),
        migrations.AlterField(
            model_name='supportticketmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
