# Generated by Django 6.0.4 on 2026-05-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_rename_fund_request_template_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='request_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
