# Generated by Django 6.0.4 on 2026-05-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_managedfilenode_trashed_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('clients', 'Clients'), ('finance', 'Finance'), ('assets', 'Asset Tracker'), ('accountability', 'Accountability'), ('support', 'Support Tickets'), ('development', 'Development'), ('file_manager', 'File Manager'), ('backup', 'Backups'), ('system', 'System'), ('users', 'Users & Roles'), ('security', 'Security')], db_index=True, max_length=32),
        ),
    ]
