# Generated by Codex on 2026-05-06

from django.db import migrations


def backfill_collapsed_role_folders(apps, schema_editor):
    ManagedFileNode = apps.get_model('core', 'ManagedFileNode')
    Group = apps.get_model('auth', 'Group')
    role_names = {
        (name or '').strip().casefold()
        for name in Group.objects.values_list('name', flat=True)
        if name and name.strip()
    }
    candidates = ManagedFileNode.objects.filter(
        parent__isnull=False,
        access_scope='shared',
        node_type__in=('folder', 'shared_folder'),
    )

    for node in candidates.only('pk', 'name', 'department_name_snapshot', 'role_name_snapshot').iterator():
        folder_name = (node.name or '').strip()
        normalized_name = folder_name.casefold()
        normalized_department = (node.department_name_snapshot or '').strip().casefold()
        normalized_role = (node.role_name_snapshot or '').strip().casefold()
        if normalized_name not in role_names:
            continue
        if normalized_role and normalized_name != normalized_role:
            continue
        if not normalized_role and normalized_department != normalized_name:
            continue

        updates = {'is_role_folder': True}
        if not normalized_role:
            updates['role_name_snapshot'] = folder_name
        ManagedFileNode.objects.filter(pk=node.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_managedfilenode_is_role_folder'),
    ]

    operations = [
        migrations.RunPython(backfill_collapsed_role_folders, migrations.RunPython.noop),
    ]
