# Generated by Django 6.0.4 on 2026-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_crmclient_crmclientmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
