# Generated by Django 6.0.4 on 2026-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_crmclient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmclient',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
