# Generated by Django 6.0.4 on 2026-05-08 09:41

from django.db import migrations, models


def clear_legacy_placeholder_email_dob(apps, schema_editor):
    CRMClient = apps.get_model('core', 'CRMClient')
    placeholder_qs = CRMClient.objects.filter(email__startswith='legacy-client-', email__endswith='@placeholder.local')
    placeholder_qs.update(email='')
    CRMClient.objects.filter(date_of_birth='1970-01-01').update(date_of_birth=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_crmclient_require_email_dob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crmclient',
            name='crmclient_email_not_blank',
        ),
        migrations.AlterField(
            model_name='crmclient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RunPython(clear_legacy_placeholder_email_dob, migrations.RunPython.noop),
    ]
