# Generated by Django 6.0.4 on 2026-05-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_crmclient_crmclient_email_not_blank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=50)),
                ('monthly_electric_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('roof_type', models.CharField(blank=True, max_length=80)),
                ('ownership', models.CharField(blank=True, max_length=20)),
                ('project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('return_on_investment', models.CharField(blank=True, max_length=80)),
                ('assigned_sales', models.CharField(blank=True, max_length=150)),
                ('sales_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='core.crmclient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sales_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created', '-created_at'],
            },
        ),
    ]
