# Generated by Django 6.0.4 on 2026-05-08 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_technical_records(apps, schema_editor):
    CRMSalesRecord = apps.get_model('core', 'CRMSalesRecord')
    CRMTechnicalRecord = apps.get_model('core', 'CRMTechnicalRecord')
    for sales_row in CRMSalesRecord.objects.all().only('id', 'created_by_id'):
        CRMTechnicalRecord.objects.get_or_create(
            sales_record_id=sales_row.id,
            defaults={'created_by_id': sales_row.created_by_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_crmsalesrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMTechnicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('team_assigned', models.CharField(blank=True, max_length=150)),
                ('system_size_kwh', models.CharField(blank=True, max_length=50)),
                ('panel_units', models.CharField(blank=True, max_length=50)),
                ('inverter_model', models.CharField(blank=True, max_length=150)),
                ('battery_model', models.CharField(blank=True, max_length=150)),
                ('net_metering', models.CharField(blank=True, max_length=80)),
                ('installation_status', models.CharField(blank=True, max_length=50)),
                ('po_number', models.CharField(blank=True, max_length=80)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_technical_records_created', to=settings.AUTH_USER_MODEL)),
                ('sales_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_record', to='core.crmsalesrecord')),
            ],
            options={
                'ordering': ['-installation_date', '-created_at'],
            },
        ),
        migrations.RunPython(backfill_technical_records, migrations.RunPython.noop),
    ]
