# Generated by Django 6.0.4 on 2026-05-10 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_crmtechnicalrecord_installation_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMTechnicalActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('schedule_set', 'Schedule Set'), ('schedule_rescheduled', 'Schedule Rescheduled')], default='schedule_set', max_length=40)),
                ('previous_installation_date', models.DateField(blank=True, null=True)),
                ('previous_installation_time', models.TimeField(blank=True, null=True)),
                ('new_installation_date', models.DateField(blank=True, null=True)),
                ('new_installation_time', models.TimeField(blank=True, null=True)),
                ('previous_team_assigned', models.CharField(blank=True, max_length=150)),
                ('new_team_assigned', models.CharField(blank=True, max_length=150)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('previous_remarks', models.TextField(blank=True)),
                ('new_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_technical_action_logs_created', to=settings.AUTH_USER_MODEL)),
                ('sales_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_action_logs', to='core.crmsalesrecord')),
                ('technical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='core.crmtechnicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
