# Generated by Django 6.0.4 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_crmtechnicalteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMTechnicalNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_days_before', models.PositiveIntegerField(default=3)),
                ('include_backlogs', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRM Technical Notification Setting',
                'verbose_name_plural': 'CRM Technical Notification Settings',
            },
        ),
    ]
