# Generated by Django 6.0.4 on 2026-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_crmtechnicalnotificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmclient',
            name='geo_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmclient',
            name='geo_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
