# Generated by Django 6.0.4 on 2026-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_formupload_subsection_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
