# Generated by Django 5.2.6 on 2026-05-14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_attendanceglobaltimemarksetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global', max_length=32, unique=True)),
                ('shift_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('time_in_open_minutes_before', models.PositiveSmallIntegerField(default=5)),
                ('late_grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('lunch_start_time', models.TimeField(default=datetime.time(12, 0))),
                ('lunch_end_time', models.TimeField(default=datetime.time(13, 0))),
                ('lunch_return_grace_minutes', models.PositiveSmallIntegerField(default=10)),
                ('time_out_start_time', models.TimeField(default=datetime.time(17, 0))),
                ('time_out_close_minutes_after', models.PositiveSmallIntegerField(default=180)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
