# Generated by Django 5.2.6 on 2026-05-14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_attendancepolicysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='time_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.attendance_time_in_upload_to),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='time_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.attendance_time_out_upload_to),
        ),
    ]
