# Generated by Django 6.0.4 on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_attendancelog_photo_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimekeepingImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timekeeping_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-imported_at']},
        ),
        migrations.CreateModel(
            name='TimekeepingImportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('employee_id', models.CharField(blank=True, default='', max_length=120)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('row_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.timekeepingimportbatch')),
            ],
            options={'ordering': ['row_number', 'id']},
        ),
    ]
