# Generated by Django 6.0.4 on 2026-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_timekeeping_import_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
