# Generated by Django 6.0.4 on 2026-05-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_crmclient_options_alter_loginevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmtechnicalrecord',
            name='net_metering_status',
        ),
    ]
