# Generated by Django 6.0.4 on 2026-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_crmclient_options_alter_loginevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmclient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-created_at'], 'permissions': (('view_crm_dashboard', 'Can view CRM dashboard section'), ('view_crm_clients_section', 'Can view CRM clients section'), ('manage_crm_clients_section', 'Can manage CRM clients section'), ('view_crm_sales_section', 'Can view CRM sales section'), ('manage_crm_sales_section', 'Can manage CRM sales section'), ('view_crm_technicals_section', 'Can view CRM technicals section'), ('manage_crm_technicals_section', 'Can manage CRM technicals section'))},
        ),
        migrations.AddField(
            model_name='crmclient',
            name='registered_in_system_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmtechnicalactionlog',
            name='action',
            field=models.CharField(choices=[('schedule_set', 'Schedule Set'), ('schedule_rescheduled', 'Schedule Rescheduled'), ('installation_updated', 'Installation Updated')], default='schedule_set', max_length=40),
        ),
    ]
