# Generated by Django 6.0.4 on 2026-05-29 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_crmsalesactivitycomment_crmsalesactivitycommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsalesactivitycomment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_replies', to='core.crmsalesactivitycomment'),
        ),
    ]
