# Generated by Django 6.0.4 on 2026-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_crmsalescommentreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsalesactivitycomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmsalesactivitycomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
