# Generated by Django 6.0.4 on 2026-06-02 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_crmsalesactivitycomment_edited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_chat_conversations', to='core.assetdepartment')),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_conversations_started', to=settings.AUTH_USER_MODEL)),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_conversations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.privatechatconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='privatechatconversation',
            index=models.Index(fields=['participant_one', 'participant_two'], name='core_privat_partici_12f755_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechatconversation',
            index=models.Index(fields=['-updated_at'], name='core_privat_updated_0ec6e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='privatechatconversation',
            constraint=models.UniqueConstraint(fields=('participant_one', 'participant_two'), name='unique_private_chat_participants'),
        ),
        migrations.AddConstraint(
            model_name='privatechatconversation',
            constraint=models.CheckConstraint(condition=models.Q(('participant_one', models.F('participant_two')), _negated=True), name='private_chat_distinct_participants'),
        ),
        migrations.AddIndex(
            model_name='privatechatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='core_privat_convers_594406_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='core_privat_sender__8fd70e_idx'),
        ),
    ]
