# Generated by Django 6.0.4 on 2026-06-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0107_privatechatconversation_privatechatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatconversation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_chat_conversations', to='auth.group'),
        ),
    ]
