# Generated by Django 6.0.4 on 2026-06-02 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_alter_privatechatconversation_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.privatechatconversation')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.privatechatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['conversation_id', 'user_id'],
                'indexes': [models.Index(fields=['conversation', 'user'], name='core_privat_convers_95f36c_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='unique_private_chat_read_state')],
            },
        ),
    ]
