# Generated by Django 6.0.4 on 2026-06-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_privatechatreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.privatechatmessage'),
        ),
    ]
