# Generated by Django 6.0.4 on 2026-06-02 09:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_privatechatmessage_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.private_chat_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.privatechatmessage')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['message', 'id'], name='core_privat_message_837246_idx')],
            },
        ),
    ]
