# Generated by Django 6.0.4 on 2026-06-03 00:42

from django.db import migrations


CRM_PERMISSION_CODENAMES = (
    'view_crm_dashboard',
    'view_crm_clients_section',
    'manage_crm_clients_section',
    'view_crm_sales_section',
    'manage_crm_sales_section',
    'view_crm_technicals_section',
    'manage_crm_technicals_section',
)


def normalize_crm_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    crm_client_ct, _ = ContentType.objects.get_or_create(app_label='core', model='crmclient')
    login_event_ct, _ = ContentType.objects.get_or_create(app_label='core', model='loginevent')

    Permission.objects.get_or_create(
        content_type=crm_client_ct,
        codename='manage_crm_admin',
        defaults={'name': 'Can administer all CRM sections'},
    )

    for codename in CRM_PERMISSION_CODENAMES:
        old_permission = Permission.objects.filter(content_type=login_event_ct, codename=codename).first()
        if not old_permission:
            continue

        new_permission = Permission.objects.filter(content_type=crm_client_ct, codename=codename).first()
        if new_permission:
            for group in old_permission.group_set.all():
                group.permissions.add(new_permission)
            for user in old_permission.user_set.all():
                user.user_permissions.add(new_permission)

        old_permission.delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_privatechatmessage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmclient',
            options={'ordering': ['-created_at'], 'permissions': (('manage_crm_admin', 'Can administer all CRM sections'), ('view_crm_dashboard', 'Can view CRM dashboard section'), ('view_crm_clients_section', 'Can view CRM clients section'), ('manage_crm_clients_section', 'Can manage CRM clients section'), ('view_crm_sales_section', 'Can view CRM sales section'), ('manage_crm_sales_section', 'Can manage CRM sales section'), ('view_crm_technicals_section', 'Can view CRM technicals section'), ('manage_crm_technicals_section', 'Can manage CRM technicals section'))},
        ),
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RunPython(normalize_crm_permissions, noop_reverse),
    ]
