# Generated by Django 6.0.4 on 2026-06-03 09:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_crm_admin_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsalesagingsetting',
            name='next_job_order_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crmsalesagingsetting',
            name='next_job_order_year',
            field=models.PositiveIntegerField(default=core.models.current_year),
        ),
        migrations.AddField(
            model_name='crmsalesrecord',
            name='job_order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
