# Generated by Django 6.0.4 on 2026-06-03 09:40

from django.db import migrations, models
from django.db.models import Q


def backfill_technical_job_order_numbers(apps, schema_editor):
	CRMSalesRecord = apps.get_model('core', 'CRMSalesRecord')
	CRMTechnicalRecord = apps.get_model('core', 'CRMTechnicalRecord')
	closed_won_records = CRMSalesRecord.objects.filter(
		Q(sales_status__iexact='closed won') | Q(sales_status__iexact='close won')
	).exclude(job_order_number='')
	for sales_record in closed_won_records:
		tech_record, _ = CRMTechnicalRecord.objects.get_or_create(sales_record_id=sales_record.id)
		if tech_record.job_order_number != sales_record.job_order_number:
			tech_record.job_order_number = sales_record.job_order_number
			tech_record.save(update_fields=['job_order_number'])


def clear_technical_job_order_numbers(apps, schema_editor):
	CRMTechnicalRecord = apps.get_model('core', 'CRMTechnicalRecord')
	CRMTechnicalRecord.objects.update(job_order_number='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_crmsalesagingsetting_next_job_order_sequence_and_more'),
    ]

    operations = [
		migrations.AddField(
			model_name='crmtechnicalrecord',
			name='job_order_number',
			field=models.CharField(blank=True, db_index=True, max_length=20),
		),
		migrations.RunPython(backfill_technical_job_order_numbers, clear_technical_job_order_numbers),
	]
