# Generated by Django 6.0.4 on 2026-06-23 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_erp_workflow_queues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('request_type', models.CharField(choices=[('purchase_requisition', 'Purchase Requisition'), ('job_request', 'Job Request for JO')], db_index=True, max_length=30)),
                ('requester_name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('jo_reference', models.CharField(blank=True, max_length=80)),
                ('request_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_requests_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_requests_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('approve_accountingrequest', 'Can approve accounting requests')],
            },
        ),
    ]
