# Generated by Django 6.0.4 on 2026-06-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_crmtechnicalrecord_purchase_order_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmtechnicalrecord',
            options={'ordering': ['-installation_date', '-created_at'], 'permissions': [('approve_crm_technical_orders', 'Can approve CRM technical JO and PO requests')]},
        ),
        migrations.AddField(
            model_name='crmtechnicalrecord',
            name='job_order_approval_status',
            field=models.CharField(blank=True, choices=[('', 'Not Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='crmtechnicalrecord',
            name='job_order_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='crmtechnicalrecord',
            name='purchase_order_approval_status',
            field=models.CharField(blank=True, choices=[('', 'Not Submitted'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='', max_length=20),
        ),
    ]
