# Generated by Django 6.0.4 on 2026-07-01 02:52

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_crm_technical_order_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.procurement_product_photo_upload_to)),
                ('item_name', models.CharField(max_length=180)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded')], db_index=True, default='included', max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_name', 'product_code'],
            },
        ),
    ]
