# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_procurementproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('currency', models.CharField(choices=[('PHP', 'PHP'), ('USD', 'USD'), ('EUR', 'EUR')], default='PHP', max_length=10)),
                ('category', models.CharField(choices=[('National', 'National'), ('Local', 'Local')], default='Local', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('deferred_payment_terms', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_suppliers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
